# Generated by Django 3.2.10 on 2023-07-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_documento_identificacion', models.CharField(max_length=13, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(max_length=350)),
                ('actividad_economica', models.CharField(max_length=350)),
                ('estado', models.CharField(max_length=15)),
                ('regimen_pagos', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
