# Generated by Django 3.2.10 on 2023-07-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_auto_20230723_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribuyente',
            name='actividad_economica',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='contribuyente',
            name='estado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contribuyente',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contribuyente',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contribuyente',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='contribuyente',
            name='regimen_pagos',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
